package modelo.ud3;
// Generated 31 mar 2023 8:53:10 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT")
public class Departamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2914670392357225425L;
	private int deptno;
	private String dname;
	private String loc;
	private Set<Empleado> employees = new HashSet<Empleado>(0);

	public Departamento() {
	}

	public Departamento(int deptno) {
		this.deptno = deptno;
	}

	public Departamento(int deptno, String dname, String loc, Set<Empleado> employees) {
		this.deptno = deptno;
		this.dname = dname;
		this.loc = loc;
		this.employees = employees;
	}

	@Id
	//@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "DEPTNO", unique = true, nullable = false)
	public int getDeptno() {
		return this.deptno;
	}

	public void setDeptno(int deptno) {
		this.deptno = deptno;
	}

	@Column(name = "DNAME", length = 20)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@Column(name = "LOC", length = 20)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Empleado> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Empleado> employees) {
		this.employees = employees;
	}

}
